### ISSUE TITLE
CPU load

### ISSUE THREAD

**Issue by to4ko** [adamoutler/pikvm-homeassistant-integration#1]
Hi!

Thanks for nice integration! If it's possible, please add CPU load sensor. Thanks!

**Comment by adamoutler** [comment]
Hello, you may wish to request this from upstream KVMD. I'm not aware of any CPU load sensor available, and I'd expect that at the /api/info location. This Integration can only monitor from available, extrapolated, or inferred data which is made available to the PiKVM API or Web Interface.

**Comment by to4ko** [comment]
ah ok! i get it! Will try with KVMD. Thanks anyway!

**Comment by adamoutler** [comment]
I mentioned this in PiKVM Dev forum https://discord.com/channels/580094191938437144/880066200959328328/1251951494572540016

**Comment by adamoutler** [comment]
CPU load is now supported in v5. Sensor should be coming in next version of PiKVM update soon.
