### ISSUE TITLE
Add 2FA support

### ISSUE THREAD

**Issue by makp0** [adamoutler/pikvm-homeassistant-integration#10]
When pikvm is protected with 2FA:
![Screenshot 2024-11-16 at 21 34 13](https://github.com/user-attachments/assets/ad952271-cd7d-4be0-be3b-ad18b67c475a)

This error originated from a custom integration.

Logger: custom_components.pikvm_ha.cert_handler
Source: custom_components/pikvm_ha/cert_handler.py:222
integration: PiKVM (documentation, issues)
First occurred: 9:31:01 PM (3 occurrences)
Last logged: 9:31:24 PM

RequestException checking PiKVM device at https://192.168.88.67: 403 Client Error: Forbidden for url: https://192.168.88.67/api/info
RequestException checking PiKVM device at http://192.168.88.67: 403 Client Error: Forbidden for url: https://192.168.88.67/api/info

**Comment by adamoutler** [comment]
That's an old version.  Please upgrade

**Comment by adamoutler** [comment]
You can add the 2fa code right after the normal password btw.  See PiKVM docs and/or support channel
